---
assets:
    job_templates:
    -   allow_simultaneous: false
        ask_credential_on_launch: false
        ask_diff_mode_on_launch: false
        ask_execution_environment_on_launch: false
        ask_forks_on_launch: false
        ask_instance_groups_on_launch: false
        ask_inventory_on_launch: false
        ask_job_slice_count_on_launch: false
        ask_job_type_on_launch: false
        ask_labels_on_launch: false
        ask_limit_on_launch: false
        ask_scm_branch_on_launch: false
        ask_skip_tags_on_launch: false
        ask_tags_on_launch: false
        ask_timeout_on_launch: false
        ask_variables_on_launch: false
        ask_verbosity_on_launch: false
        become_enabled: false
        description: ''
        diff_mode: false
        execution_environment: null
        extra_vars: ''
        force_handlers: false
        forks: 0
        host_config_key: ''
        inventory:
            name: Demo Inventory
            organization:
                name: Default
                type: organization
            type: inventory
        job_slice_count: 1
        job_tags: ''
        job_type: run
        limit: ''
        name: Demo Job Template
        natural_key:
            name: Demo Job Template
            organization:
                name: Default
                type: organization
            type: job_template
        playbook: hello_world.yml
        prevent_instance_group_fallback: false
        project:
            name: Demo Project
            organization:
                name: Default
                type: organization
            type: project
        related:
            credentials:
            -   credential_type:
                    kind: ssh
                    name: Machine
                    type: credential_type
                name: Demo Credential
                organization: null
                type: credential
            labels: []
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
            schedules: []
            survey_spec: {}
        scm_branch: ''
        skip_tags: ''
        start_at_task: ''
        survey_enabled: false
        timeout: 0
        use_fact_cache: false
        verbosity: 0
        webhook_credential: null
        webhook_service: ''
changed: false
failed: false
...
