# default gitleaks configuration file
#  https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
[allowlist]
description = "global allow lists"
paths = [
    '''satellite/ansible\.cfg$''',
    '''script/rhel7\.lab\.example\.com\.ks$''',
  ]
