---
# This playbook prints a simple debug message
- name: Echo
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Print debug message
      ansible.builtin.debug:
        msg: Hello, world!
...
