---
# this code based on 
# https://github.com/sscheib/ansible_satellite/blob/main/20_satellite_openscap.yml
# Satellite API guide
# https://access.redhat.com/documentation/en-us/red_hat_satellite/6.14/html-single/api_guide/index
# Satellite API resources
# https://satellite.build.example.com/apidoc/v2.html
#

- name: Check capsule feature Openscap
  hosts: localhost
  gather_facts: false
  vars_files:
    - openscap-vars.yml

  tasks:

    # a simpler CLI way of reading satellite resources is to run
    #  hammer capsule info --name satellite.example.com
    #
    - name: Get Satellite resource info
      redhat.satellite.resource_info:
        username: '{{ sat_username }}'
        password: '{{ sat_password }}'
        server_url: '{{ sat_server_url }}'
        validate_certs: '{{ satellite_validate_certs }}'
        resource: 'capsules'
        search: 'name = {{ satellite_fqdn }}'
      register: '__t_capsules'

    - name: Display resources
      ansible.builtin.debug:
        var: '__t_capsules'
        verbosity: 1

    - name: Ensure only one result is returned
      ansible.builtin.assert:
        that:
              - __t_capsules.resources is defined
              - __t_capsules.resources is not string
              - __t_capsules.resources is not mapping
              - __t_capsules.resources is iterable
              - __t_capsules.resources | length == 1
              - __t_capsules.resources[0].id is defined
              - __t_capsules.resources[0].id is number
              - __t_capsules.resources[0].id | string | int == __t_capsules.resources[0].id | int

    - name: Check Openscap feature
      ansible.builtin.set_fact:
        openscap_enabled: true
      when:  __t_capsules['resources'][0]['features'] | selectattr('name','equalto','Openscap') | list | count > 0

    - name: Fail if no Openscap feature
      ansible.builtin.fail:
      when: not openscap_enabled



